project_id = "ezdcqzoeemfzdbxsycay"

[functions.send-contact-email]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false
